### ISSUE TITLE
libappindicator build failure

### ISSUE THREAD

**Issue by faveoled** [flathub/shared-modules#286]
```
configure: error: Package requirements (gtk+-3.0 >= 2.91
                                     glib-2.0 >= 2.26
                                     gio-2.0 >= 2.26
                                     indicator3-0.4 >= 0.4.93
                                     dbusmenu-gtk3-0.4 >= 0.5.90) were not met:

Package 'indicator3-0.4', required by 'virtual:world', not found
Package 'dbusmenu-gtk3-0.4', required by 'virtual:world', not found
```
My manifest snippet:
```
runtime: org.gnome.Platform
runtime-version: '45'
sdk: org.gnome.Sdk
#
# omitted
#
modules:
  - shared-modules/dbus-glib/dbus-glib.json
  - shared-modules/libappindicator/libappindicator-gtk3-12.10.json
```
Any ideas?

**Comment by hfiguiere** [comment]
remove `shared-modules/dbus-glib/dbus-glib.json` for starter

**Comment by faveoled** [comment]
> remove `shared-modules/dbus-glib/dbus-glib.json` for starter

I had it removed before, nothing changes

**Comment by TingPing** [comment]
I cannot reproduce. Using this exact manifest:

```yml
id: org.example.test
runtime: org.gnome.Platform
runtime-version: '45'
sdk: org.gnome.Sdk
modules:
  - shared-modules/libappindicator/libappindicator-gtk3-12.10.json
```

`flatpak-builder _build test.yml`
