### ISSUE TITLE
libayatana-appindicator does not support Gnome runtime 47.

### ISSUE THREAD

**Issue by Erven2016** [flathub/shared-modules#330]
There is my manifest. I'm using Gnome runtime 47 for more recent glibc version.

```yaml
id: io.github.Martichou.rquickshare
runtime: org.gnome.Platform
runtime-version: "47"
sdk: org.gnome.Sdk
command: start-rquickshare
separate-locales: false
finish-args:
  - --share=network
  - --socket=wayland
  - --socket=fallback-x11
  - --device=dri
  - --talk-name=org.kde.StatusNotifierWatcher

  # todo: presist config file
  # todo: allow write access of host:~/Downloads
modules:
  - shared-modules/libayatana-appindicator/libayatana-appindicator-gtk3.json
  - name: rquickshare
    buildsystem: simple
    build-commands:
      - bsdtar -Oxf rquickshare.deb 'data.tar.gz' | bsdtar -xf -
      - install -Dm 755 usr/bin/rquickshare -t "${FLATPAK_DEST}/bin"
      - install -Dm 755 start-rquickshare.sh "${FLATPAK_DEST}/bin/start-rquickshare"

      - # todo: install desktop files and icons later
    sources:
      - type: file
        url: "https://github.com/Martichou/rquickshare/releases/download/v0.11.2/r-quick-share-main_v0.11.2_glibc-2.39_amd64.deb"
        sha256: "34dfeefc9ff6060a8c0ed14ebb494bdbc0509edfe1b0c87a081c5914216cf566"
        only-arches:
          - x86_64
        dest-filename: rquickshare.deb
      - type: file
        path: start-rquickshare.sh
      # todo: add x-data-checker later
```

But when runinng flatpak-builder and it throws error `Package 'libayatana-ido3-0.4' not found`. And there is not problem if I use Gnome runtime 46.

![image](https://github.com/user-attachments/assets/19f49e83-924c-428b-aceb-cd54c6c1079d)
